#' @title Plot EPC or SEPC from piMIMIC Results
#'
#' @description
#' Generates bar plots of unstandardized (EPC) or standardized (SEPC.ALL)
#' expected parameter change for uniform and non-uniform DIF, facilitating
#' the interpretation of DIF effects from \code{\link{piMIMIC}} output.
#'
#' @param resultados List of results generated by \code{\link{piMIMIC}}.
#' @param cov Name of the covariate used in \code{\link{piMIMIC}}.
#' @param metric Character. Metric to plot: either `"EPC"` or `"SEPC.ALL"`
#'        (default is `"SEPC.ALL"`).
#' @param theme_option ggplot2 theme (default is `theme_minimal()`).
#' @param bar_colors Named character vector. Colors for DIF types.
#'        Default: `c("Uniform DIF" = "blue", "Non-uniform DIF" = "red")`.
#' @param cutoff.line Numeric or vector. Optional horizontal line(s) indicating
#'        a DIF cutoff. If `NULL` (default), no line is drawn.
#'        Example: `c(-0.10, 0.10)`.
#'
#' @return A ggplot bar plot, or `NULL` if insufficient data.
#'
#' @details
#' `plotpiMIMIC` requires as input the output list from `piMIMIC`, specifically
#' the `$SEPC.uDIF` and `$SEPC.nuDIF` components. It combines them and plots
#' either the unstandardized (EPC) or standardized (SEPC.ALL) expected parameter
#' change for each item, with separate bars for uniform and non-uniform DIF.
#'
#' The function uses `ggplot2`. If the data are missing, it returns `NULL` with
#' a warning.
#'
#' @examples
#' \dontrun{
#' ### Example : simulated data -------------
#' set.seed(123)
#' Exmp1.data <- data.frame(
#'   grp = sample(0:1, 100, replace = TRUE),  # Group variable
#'   item1 = sample(1:5, 100, replace = TRUE),
#'   item2 = sample(1:5, 100, replace = TRUE),
#'   item3 = sample(1:5, 100, replace = TRUE),
#'   item4 = sample(1:5, 100, replace = TRUE))
#'
#' res <- piMIMIC(data = Exmp1.data , items = c("item1","item2","item3"), cov = "grp")
#' plotpiMIMIC(res, cov = "grp")
#' plotpiMIMIC(res, cov = "grp", metric = "EPC", cutoff.line = c(-0.10, 0.10))
#' }
#'
#' @importFrom ggplot2 ggplot aes geom_bar geom_hline coord_flip labs scale_fill_manual theme_minimal
#' @importFrom rlang sym .data
#'
#' @export
plotpiMIMIC <- function(resultados, cov,
                        metric = "SEPC.ALL",
                        theme_option = ggplot2::theme_minimal(),
                        bar_colors = c("Uniform DIF" = "blue",
                                       "Non-uniform DIF" = "red"),
                        cutoff.line = NULL) {  # <-- ahora es NULL por defecto

  # Validate metric
  if (!metric %in% c("EPC", "SEPC.ALL")) {
    stop("Error: 'metric' must be 'EPC' or 'SEPC.ALL'.")
  }

  # Check if both SEPC components exist and have data
  if (is.null(resultados$SEPC.uDIF) || is.null(resultados$SEPC.nuDIF)) {
    warning("SEPC data not found in 'resultados'. Did you run piMIMIC()?")
    return(NULL)
  }

  if (nrow(resultados$SEPC.uDIF) == 0 && nrow(resultados$SEPC.nuDIF) == 0) {
    warning("SEPC data frames are empty. No DIF effects to plot.")
    return(NULL)
  }

  # Combine both data frames with a Type column
  df_u <- resultados$SEPC.uDIF
  df_u$Type <- "Uniform DIF"

  df_nu <- resultados$SEPC.nuDIF
  df_nu$Type <- "Non-uniform DIF"

  df_combined <- rbind(df_u, df_nu)

  # Ensure Type is a factor with desired order
  df_combined$Type <- factor(df_combined$Type,
                             levels = c("Uniform DIF", "Non-uniform DIF"))

  # Build the plot
  p <- ggplot2::ggplot(df_combined,
                       ggplot2::aes(x = .data$Item,
                                    y = !!rlang::sym(metric),
                                    fill = .data$Type)) +
    ggplot2::geom_bar(stat = "identity", position = "dodge") +
    ggplot2::coord_flip() +
    ggplot2::labs(
      title = paste(metric, "by Item - Covariate:", cov),
      x = "Items",
      y = if (metric == "EPC") "Expected Parameter Change" else "Standardized EPC"
    ) +
    ggplot2::scale_fill_manual(values = bar_colors) +
    theme_option

  # Add cutoff line(s) only if cutoff.line is provided
  if (!is.null(cutoff.line)) {
    p <- p + ggplot2::geom_hline(yintercept = cutoff.line,
                                 linetype = "dashed",
                                 color = "black")
  }

  # Print the plot (so it appears even if not assigned)
  print(p)
  invisible(p)
}
